### ISSUE TITLE
Check out vim-sandwich as an alternative to vim-surround

### ISSUE THREAD

**Issue by ErichDonGubler** [erichdongubler-dotfiles/vim#6]
https://github.com/machakann/vim-sandwich

**Comment by mb720** [comment]
What are the advantages of vim-sandwich compared to vim-surround in your opinion?

**Comment by ErichDonGubler** [comment]
The differences I've noticed so far are as follows:

## Pros

* It's nice to have the [magic surround functionality](https://github.com/machakann/vim-sandwich/blob/4811a5c66816413bf6a7b5d0ee0de4ef9e1fbdc9/doc/sandwich.txt#L265) for really common surroundings like functions and tags. `vim-surround` handles the latter and not the former. Furthermore, `vim-sandwich` accepts [Emmet-inspired syntax](), which as a former web dev is sweet.
* Customization is much better-implemented. Referring back to [the commit](https://github.com/erichdongubler-dotfiles/vim/commit/0c8cc6b657faa645d18050d5b2754739877bced0) where I actually implemented this issue, customizing `vim-surround` looks like this:

    ``` viml
    let b:surround_100 = "dbg!(\r)"
    let b:surround_111 = "Some(\r)"
    let b:surround_114 = "Ok(\r)"
    let b:surround_118 = "vec![\r]"
    let b:surround_66 = "Box<\r>"
    let b:surround_79 = "Option<\r>"
    let b:surround_82 = "Result<\r>"
    let b:surround_98 = "Box::new(\r)"
    ```

    ...meanwhile, in `vim-sandwich` it looks like this:

    ```viml
    fun! s:AddRustSandwichBinding(input, start, end)
    	let g:sandwich#recipes += [{
    		\ 'buns': [a:start, a:end],
    		\ 'filetype': ['rust'],
    		\ 'input': [a:input],
    		\ 'nesting': 1,
    		\ 'indent': 1
    	\ }]
    endf
    call s:AddRustSandwichBinding('d', 'dbg!(', ')')
    call s:AddRustSandwichBinding('o', 'Some(', ')')
    call s:AddRustSandwichBinding('r', 'Ok(', ')')
    call s:AddRustSandwichBinding('v', 'vec![', ']')
    call s:AddRustSandwichBinding('b', 'Box::new(', ')')
    call s:AddRustSandwichBinding('B', 'Box<', '>')
    call s:AddRustSandwichBinding('O', 'Option<', '>')
    call s:AddRustSandwichBinding('R', 'Result<', '>')
    ```

    So, fairly comparable if you're willing to write some boilerplate for `vim-sandwich`. The latter is actually much better in terms of functionality, because as far as I can tell custom surroundings for `vim-surround` only support an add operation...meanwhile, `vim-sandwich` correctly implements add, delete, and replace.
* The UI is waaay better. Having visual hints as to what happened saves quite a bit of sanity. That might not be persuasive to your average Vimmer...unless it's just the cherry on top. :)

The only con I've found so far is that line-selected handling isn't as good -- there's reindentation support, but out of the box it's not what I want. I'll take it with the other good stuff, though!

**Comment by ErichDonGubler** [comment]
`vim-sandwich` has been really great, and I don't miss `vim-surround`. So I'm done with this! Woot!
